// Auto-generated by KWS_MFCC_Training.ipynb
// DO NOT EDIT MANUALLY
#pragma once
#include <stdint.h>
#include <avr/pgmspace.h>

#define KWS_NUM_CLASSES  4
#define KWS_N_MFCC       13
#define KWS_N_MELS       26
#define KWS_N_FRAMES     14
#define KWS_FRAME_LEN    256
#define KWS_HOP_LEN      128
#define KWS_FFT_SIZE     256
#define KWS_SAMPLE_RATE  16000

static const char* KWS_CLASS_NAMES[4] = {
  "clap",
  "tap",
  "snap",
  "whistle",
};

// shape: 13
static const float KWS_NORM_MEAN[13] PROGMEM = {
  -72.48076630f,
  6.73307896f,
  -0.14364460f,
  0.32754079f,
  0.78811944f,
  0.87490582f,
  0.36388144f,
  -0.86596590f,
  -0.69031042f,
  0.15203932f,
  0.80408359f,
  0.86096555f,
  -0.18063049f
};

// shape: 13
static const float KWS_NORM_STD[13] PROGMEM = {
  9.71952915f,
  8.70678711f,
  4.15249920f,
  2.16239715f,
  1.57669783f,
  3.06743288f,
  1.90753782f,
  1.44058359f,
  1.78330529f,
  0.84655029f,
  1.87756228f,
  1.24790919f,
  0.95789772f
};
